# ---------------- #
#   Main Configs   #
# ---------------- #
baseurl:
url: https://3dincrement18.github.io
date_format: "ordinal"
title: 3D Increment
subtitle: "3D 打印改变生活"
description: "3D increment blog"
keywords: 3D printing, increment, recruit
#timezone: Asia/Shanghai
encoding: "utf-8"
side_bar_repo_limit: 5

# ---------------- #
#      Author      #
# ---------------- #
author: 3D Increment
organization: 3D Increment
organization_url: https://3dincrement18.github.io
github_username: 3dincrement18
location: Qingdao, China
email: 3dincremnt@gmail.com

# ---------------- #
#    Navigation    #
# ---------------- #
navs:
  -
    href: /
    label: 首页

  -
    href: /member/
    label: 团队
    
  -
    href: /publications/
    label: 成果

  -
    href: /categories/
    label: blog

  -
    href: /wiki/
    label: wiki

  -
    href: /links/
    label: 链接

# ---------------- #
#       RSS        #
# ---------------- #
subscribe_rss: /feed.xml

# ---------------- #
#      Jekyll      #
# ---------------- #
markdown: kramdown
kramdown:
    input: GFM
highlighter: rouge
paginate: 8
lsi: false
quiet: false
excerpt_separator: "\n\n"
permalink: /:year/:month/:day/:title/
gems:
    - bootstrap
    - jekyll-github-metadata
    - rouge
#     - jekyll-html-pipeline
    - jekyll-paginate
    - jekyll-sitemap
    - jekyll-feed
    - jemoji
#     - jekyll-mentions
collections:
    wiki:
        output: true
        permalink: /wiki/:path/
               
    member:
        output: true
        permalink: /member/:path/

repository: 3dincrement18/3dincrement18.github.io

# ---------------- #
#      Comments    #
# ---------------- #
# support provider: disqus, gitment, gitalk
comments_provider: gitalk
# !!!重要!!! 请修改下面这些信息为你自己申请的
# !!!Important!!! Please modify infos below to yours
# https://disqus.com
disqus:
    username: 
# https://imsun.net/posts/gitment-introduction/
#gitment:
#    owner: 3dincrement
#    repo: 3dincrement.github.io
#   oauth:
#        client_id: 6aac903760c8b3b313e8
#        client_secret: 0696db07ba2897d037fcac78c3575d317ce990c6
# https://github.com/gitalk/gitalk#install
gitalk:
    owner: 3dincrement18
    repo: 3dincrement18.github.io
    clientID: ee622ca2daf869d1e412
    clientSecret: 9d1a6474f4c5b32004035545b3c0cd98996fa3a3
# 在使用其它评论组件时可点击显示 Disqus
lazy_load_disqus : false

# ---------------- #
#      Search      #
# ---------------- #
simple_jekyll_search:
    # 是否支持全文搜索
    fulltext: false
    # 最多显示多少条搜索结果
    limit: 10

# ---------------- #
#    Analytics     #
# ---------------- #
google:
    analytics_id: UA-80669434-1
